site_name: 'TSWoW Wiki'
site_description: 'Port of the Read the Docs theme to Jekyll to use with GitHub Pages.'
repo_url: 'https://github.com/carlosperate/tswow-wiki-new'
repo_name: 'GitHub'
docs_dir: 'docs/'
site_dir: '_site_mkdocs/'
theme: 'readthedocs'
prev_next_buttons_location: 'both'
copyright: 'Carlos Pereira Atencio'
